CREATE TABLE photoGram_albums (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    album_name TEXT NOT NULL,
    img_url TEXT,
    user_id INTEGER REFERENCES photoGram_users(id) ON DELETE CASCADE
)