CREATE TBALE photoGram_images (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    imgUrl TEXT NOT NULL,
    caption TEXT,
    tags TEXT,
    album_id INTEGER REFERENCES photoGram_albums(id) ON DELETE CASCADE,
    date_created TIMESTAMP DEFAULT now() NOT NULL

)