CREATE TABLE IF NOT EXISTS photoGram_images (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    img_url TEXT NOT NULL,
    caption TEXT,
    tags TEXT,
    user_id INTEGER REFERENCES photoGram_users(id) ON DELETE CASCADE,
    album_id INTEGER NULL REFERENCES photoGram_albums(id) ON DELETE CASCADE,
    date_created DATE DEFAULT now()
);